name: PR-Actions

on: pull_request

jobs:
  Linting:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        python-version: ['3.12']
        os: ['ubuntu-latest']
    name: Linting OS ${{ matrix.os }} - Python ${{ matrix.python-version }}
    steps:
      - uses: actions/checkout@v2

      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      # Need to update if we support other OS's
      - name: Cache PIP Install
        uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-${{ matrix.python-version }}-pip-lint-${{ hashFiles('**/setup.py') }}-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-${{ matrix.python-version }}-pip-lint

      - name: Run Linting
        run: |
          pip install black flake8
          make lint

  PyTest:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        python-version: [ '3.8', '3.9', '3.10', '3.11','3.12']
        os: ['ubuntu-latest']
    name: PyTests OS ${{ matrix.os }} - Python ${{ matrix.python-version }}
    steps:
      - uses: actions/checkout@v2

      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      # Need to update if we support other OS's
      - name: Cache PIP Install
        uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-${{ matrix.python-version }}-pip-install-${{ hashFiles('**/setup.py') }}-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-${{ matrix.python-version }}-pip-install

      - name: Make Deps
        run: make deps

      - name: Run Tests
        run: make test

  CodeCoverage:

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        python-version: ['3.12']
        os: ['ubuntu-latest']

    env:
      OS: ${{ matrix.os }}
      PYTHON: ${{ matrix.python-version }}

    name: Code Coverage OS ${{ matrix.os }} - Python ${{ matrix.python-version }}
    steps:
      - uses: actions/checkout@v2

      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      # Need to update if we support other OS's
      - name: Cache PIP Install
        uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-${{ matrix.python-version }}-pip-coverage-${{ hashFiles('**/setup.py') }}-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-${{ matrix.python-version }}-pip-coverage

      - name: Make Deps
        run: |
          make deps
          pip install pytest
          pip install pytest-cov

      - name: Generate coverage report
        continue-on-error: true
        run: |
          coverage run --source brewtils -m pytest test --tb=no
          coverage report -m
          coverage xml

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1

  pull-request-links:
    runs-on: ubuntu-latest
    steps:
      - name: Make Deps
        run: |
          make docs
      - name: Build Links
        uses: readthedocs/actions/preview@v1
        with:
          project-slug: "brewtils-preview"